# deploy-cf-pages.ps1 — 构建并部署 Web 端到 Cloudflare Pages
# Usage: .\deploy-cf-pages.ps1
# Prereq: 已通过 npx wrangler login 登录 Cloudflare 账号

param(
    [string]$ProjectName = "img-toolbox"
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$distWeb = Join-Path $root "dist\web"

Write-Host "1/3  Building dist/web/ ..." -ForegroundColor Cyan
# build.ps1 emits the site-root dist/web/index.html itself and asserts that every
# asset it references exists under dist/web/. No per-path patching happens here:
# rewriting generated paths with fixed regular expressions silently no-ops as soon
# as the generated paths change, which is exactly how a broken deploy shipped.
powershell -ExecutionPolicy Bypass -File (Join-Path $root "build.ps1")
if ($LASTEXITCODE -ne 0) { Write-Host "Build failed!" -ForegroundColor Red; exit 1 }

if (-not (Test-Path (Join-Path $distWeb "index.html"))) {
    Write-Host "dist/web/index.html was not generated by the build - refusing to deploy." -ForegroundColor Red
    exit 1
}

Write-Host "2/3  Checking the artifact against the site root ..." -ForegroundColor Cyan
# Independent, artifact-side check: recompute every first-load request the way a
# browser would from "/" and fail if any of them would 404. Cheap, needs no browser,
# and runs on the produced files rather than on the script that produced them.
node (Join-Path $root "scripts\verify-web-root-load.mjs") $distWeb
if ($LASTEXITCODE -ne 0) { Write-Host "Artifact check failed - refusing to deploy." -ForegroundColor Red; exit 1 }

Write-Host "3/3  Deploying to Cloudflare Pages (project: $ProjectName) ..." -ForegroundColor Cyan
npx wrangler pages deploy $distWeb --project-name $ProjectName
if ($LASTEXITCODE -ne 0) { Write-Host "Deploy failed!" -ForegroundColor Red; exit 1 }

Write-Host "Done!" -ForegroundColor Green
